export interface TriviaQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  correctAnswer: string;
  explanation: string;
  category: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  hostCommentary: string;
  funFact: string;
  groundingSources?: { title?: string; uri?: string }[];
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // ==================== SCIENCE & NATURE ====================
  {
    id: 'sci_e1',
    question: 'Which chemical element has the atomic symbol "Au"?',
    options: ['Silver', 'Gold', 'Argon', 'Aluminum'],
    correctIndex: 1,
    correctAnswer: 'Gold',
    explanation: 'Au comes from the Latin word for gold, "aurum", meaning shining dawn.',
    category: 'science_nature',
    difficulty: 'Easy',
    hostCommentary: 'Golden opportunity for an early lead right here!',
    funFact: 'All the gold ever mined worldwide would fit into a cube roughly 22 meters on each side.',
  },
  {
    id: 'sci_e2',
    question: 'What is the closest planet to the Sun in our Solar System?',
    options: ['Venus', 'Mars', 'Mercury', 'Earth'],
    correctIndex: 2,
    correctAnswer: 'Mercury',
    explanation: 'Mercury orbits closest to the Sun at an average distance of about 58 million kilometers.',
    category: 'science_nature',
    difficulty: 'Easy',
    hostCommentary: 'Don’t let the celestial pressure cook you on this one!',
    funFact: 'Despite being closest to the Sun, Venus is hotter than Mercury due to its dense greenhouse atmosphere.',
  },
  {
    id: 'sci_e3',
    question: 'What gas do plants primarily absorb from the atmosphere during photosynthesis?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Methane'],
    correctIndex: 1,
    correctAnswer: 'Carbon Dioxide',
    explanation: 'Plants absorb CO2 and water, utilizing sunlight to produce glucose and oxygen.',
    category: 'science_nature',
    difficulty: 'Easy',
    hostCommentary: 'Take a deep breath and let your biology knowledge blossom.',
    funFact: 'The Amazon rainforest produces roughly 6% of the world’s oxygen supply.',
  },
  {
    id: 'sci_m1',
    question: 'What is the most abundant element in the Earth’s atmosphere by volume?',
    options: ['Oxygen', 'Carbon Dioxide', 'Argon', 'Nitrogen'],
    correctIndex: 3,
    correctAnswer: 'Nitrogen',
    explanation: 'Nitrogen accounts for approximately 78% of Earth’s atmosphere, followed by oxygen at about 21%.',
    category: 'science_nature',
    difficulty: 'Medium',
    hostCommentary: 'Careful not to suffocate on the obvious trap here!',
    funFact: 'Liquid nitrogen boils at -195.8°C (-320°F).',
  },
  {
    id: 'sci_m2',
    question: 'How many pairs of chromosomes are normally found in a human somatic cell?',
    options: ['21', '23', '24', '46'],
    correctIndex: 1,
    correctAnswer: '23',
    explanation: 'Humans typically have 23 pairs of chromosomes, totaling 46 individual chromosomes.',
    category: 'science_nature',
    difficulty: 'Medium',
    hostCommentary: 'Let’s see if your genetic memory serves you well.',
    funFact: 'If unwound, the DNA in all your body’s cells would stretch from Earth to Pluto and back multiple times.',
  },
  {
    id: 'sci_m3',
    question: 'What is the hardest naturally occurring mineral on Earth on the Mohs scale?',
    options: ['Topaz', 'Corundum', 'Diamond', 'Quartz'],
    correctIndex: 2,
    correctAnswer: 'Diamond',
    explanation: 'Diamond is ranked at a perfect 10 on the Mohs hardness scale.',
    category: 'science_nature',
    difficulty: 'Medium',
    hostCommentary: 'Time to prove whether your intellect is sparkling or under pressure!',
    funFact: 'Diamonds are composed purely of carbon atoms arranged in a tetrahedral crystal lattice.',
  },
  {
    id: 'sci_h1',
    question: 'What subatomic particle was discovered at CERN’s Large Hadron Collider in July 2012?',
    options: ['Top Quark', 'Higgs Boson', 'Tau Neutrino', 'Graviton'],
    correctIndex: 1,
    correctAnswer: 'Higgs Boson',
    explanation: 'The Higgs boson explains how fundamental particles gain mass through the Higgs field.',
    category: 'science_nature',
    difficulty: 'Hard',
    hostCommentary: 'Quantum physics in the house! Particle accelerators at full throttle!',
    funFact: 'Peter Higgs and François Englert won the 2013 Nobel Prize in Physics for predicting it in 1964.',
  },
  {
    id: 'sci_h2',
    question: 'What is the SI unit of electrical capacitance named after a British experimentalist?',
    options: ['Henry', 'Farad', 'Coulomb', 'Siemens'],
    correctIndex: 1,
    correctAnswer: 'Farad',
    explanation: 'The farad (F) is named after Michael Faraday and measures electrical capacitance.',
    category: 'science_nature',
    difficulty: 'Hard',
    hostCommentary: 'High voltage intellectual challenge! Don’t short-circuit now!',
    funFact: 'One farad is a massive amount of capacitance; most consumer capacitors are rated in microfarads.',
  },

  // ==================== WORLD HISTORY ====================
  {
    id: 'hist_e1',
    question: 'Which ancient civilization constructed the Great Pyramids of Giza?',
    options: ['Ancient Romans', 'Ancient Egyptians', 'Mayans', 'Babylonians'],
    correctIndex: 1,
    correctAnswer: 'Ancient Egyptians',
    explanation: 'The Great Pyramids of Giza were built by Ancient Egyptians during the Old Kingdom period.',
    category: 'world_history',
    difficulty: 'Easy',
    hostCommentary: 'An ancient foundational question for modern champions.',
    funFact: 'The Great Pyramid was the tallest man-made structure in the world for over 3,800 years.',
  },
  {
    id: 'hist_e2',
    question: 'In which year did the United States declare its independence from Britain?',
    options: ['1774', '1776', '1789', '1812'],
    correctIndex: 1,
    correctAnswer: '1776',
    explanation: 'The Declaration of Independence was adopted by the Continental Congress on July 4, 1776.',
    category: 'world_history',
    difficulty: 'Easy',
    hostCommentary: 'Ring the Liberty Bell! A classic American history benchmark.',
    funFact: 'John Adams and Thomas Jefferson, both signers and presidents, both died on July 4, 1826.',
  },
  {
    id: 'hist_m1',
    question: 'Which Roman general crossed the Rubicon river in 49 BC, sparking a civil war?',
    options: ['Mark Antony', 'Julius Caesar', 'Pompey the Great', 'Scipio Africanus'],
    correctIndex: 1,
    correctAnswer: 'Julius Caesar',
    explanation: 'Julius Caesar’s crossing of the Rubicon crossed the point of no return, giving rise to the famous idiom.',
    category: 'world_history',
    difficulty: 'Medium',
    hostCommentary: 'The die is cast! Which path will you choose?',
    funFact: 'Suetonius recorded Caesar uttering the iconic Latin phrase "Alea iacta est" as he crossed.',
  },
  {
    id: 'hist_m2',
    question: 'In what year did the Apollo 11 mission first land humans on the Moon?',
    options: ['1965', '1968', '1969', '1972'],
    correctIndex: 2,
    correctAnswer: '1969',
    explanation: 'Neil Armstrong and Buzz Aldrin set foot on the lunar surface on July 20, 1969.',
    category: 'world_history',
    difficulty: 'Medium',
    hostCommentary: 'One small step for a contender, one giant leap for the leaderboard!',
    funFact: 'The Apollo 11 Lunar Module guidance computer had only about 4 kilobytes of RAM.',
  },
  {
    id: 'hist_h1',
    question: 'Which treaty signed in 1648 effectively ended the Thirty Years’ War in Europe?',
    options: ['Treaty of Utrecht', 'Peace of Westphalia', 'Treaty of Versailles', 'Edict of Nantes'],
    correctIndex: 1,
    correctAnswer: 'Peace of Westphalia',
    explanation: 'The Peace of Westphalia established the modern concept of sovereign statehood and diplomacy.',
    category: 'world_history',
    difficulty: 'Hard',
    hostCommentary: 'Deep historical diplomacy on trial. Only true historians survive this.',
    funFact: 'The peace was negotiated across two different cities, Münster and Osnabrück, due to religious disputes.',
  },
  {
    id: 'hist_h2',
    question: 'Who was the last ruling Pharaoh of the Ptolemaic Kingdom of Egypt?',
    options: ['Hatshepsut', 'Nefertiti', 'Cleopatra VII', 'Arsinoe IV'],
    correctIndex: 2,
    correctAnswer: 'Cleopatra VII',
    explanation: 'Cleopatra VII Philopator was the last active ruler of Ptolemaic Egypt before Roman annexation.',
    category: 'world_history',
    difficulty: 'Hard',
    hostCommentary: 'The sands of antiquity await your sovereign verdict.',
    funFact: 'Cleopatra was linguistically gifted and was the only Ptolemaic monarch known to have learned Egyptian.',
  },

  // ==================== GEOGRAPHY & WONDERS ====================
  {
    id: 'geo_e1',
    question: 'What is the largest ocean on Earth by surface area?',
    options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
    correctIndex: 3,
    correctAnswer: 'Pacific Ocean',
    explanation: 'The Pacific Ocean covers more than 30% of the Earth’s entire surface area.',
    category: 'geography_wonders',
    difficulty: 'Easy',
    hostCommentary: 'Navigate these calm waters or get lost at sea!',
    funFact: 'The Pacific Ocean is actually larger than all of Earth’s landmasses combined.',
  },
  {
    id: 'geo_e2',
    question: 'Which country is home to the ancient ruins of Machu Picchu?',
    options: ['Chile', 'Peru', 'Bolivia', 'Colombia'],
    correctIndex: 1,
    correctAnswer: 'Peru',
    explanation: 'Machu Picchu is a 15th-century Inca citadel located in the Eastern Cordillera of southern Peru.',
    category: 'geography_wonders',
    difficulty: 'Easy',
    hostCommentary: 'Pack your hiking boots and aim high!',
    funFact: 'It was built using the ashlar technique, where stone blocks are fitted together without mortar.',
  },
  {
    id: 'geo_m1',
    question: 'What is the capital city of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctIndex: 2,
    correctAnswer: 'Canberra',
    explanation: 'Canberra was chosen as the compromise capital in 1908 between rival cities Sydney and Melbourne.',
    category: 'geography_wonders',
    difficulty: 'Medium',
    hostCommentary: 'A classic trivia landmine! Did you dodge the Sydney trap?',
    funFact: 'The name Canberra is derived from a local Ngunnawal word thought to mean "meeting place".',
  },
  {
    id: 'geo_m2',
    question: 'Which of the following is the deepest oceanic trench on Earth?',
    options: ['Java Trench', 'Puerto Rico Trench', 'Mariana Trench', 'Tonga Trench'],
    correctIndex: 2,
    correctAnswer: 'Mariana Trench',
    explanation: 'The Challenger Deep within the Mariana Trench drops to nearly 11,000 meters (36,000 feet).',
    category: 'geography_wonders',
    difficulty: 'Medium',
    hostCommentary: 'Diving deep into the abyss for this point!',
    funFact: 'Water pressure at the bottom exceeds 1,000 atmospheres, equivalent to an elephant standing on your thumb.',
  },
  {
    id: 'geo_h1',
    question: 'Which landlocked country is completely surrounded by South Africa?',
    options: ['Swaziland / Eswatini', 'Botswana', 'Lesotho', 'Namibia'],
    correctIndex: 2,
    correctAnswer: 'Lesotho',
    explanation: 'Lesotho is an enclaved sovereign country completely surrounded by South Africa.',
    category: 'geography_wonders',
    difficulty: 'Hard',
    hostCommentary: 'Geography masters, this is your geographic border showdown.',
    funFact: 'Lesotho is the only independent state in the world that lies entirely above 1,000 meters in elevation.',
  },
  {
    id: 'geo_h2',
    question: 'What is the longest river entirely located within the European continent?',
    options: ['Danube', 'Volga', 'Rhine', 'Dnieper'],
    correctIndex: 1,
    correctAnswer: 'Volga',
    explanation: 'Flowing entirely through European Russia, the Volga spans approximately 3,530 km (2,193 miles).',
    category: 'geography_wonders',
    difficulty: 'Hard',
    hostCommentary: 'Ride the river rapids of European geography!',
    funFact: 'Eleven of the twenty largest cities in Russia, including the capital area, are in the Volga’s drainage basin.',
  },

  // ==================== POP CULTURE & GAMING ====================
  {
    id: 'pop_e1',
    question: 'What is the name of Mario’s green-clad twin brother in Nintendo games?',
    options: ['Wario', 'Luigi', 'Waluigi', 'Toad'],
    correctIndex: 1,
    correctAnswer: 'Luigi',
    explanation: 'Luigi first appeared in the 1983 Game & Watch title and Mario Bros. arcade game.',
    category: 'pop_culture_gaming',
    difficulty: 'Easy',
    hostCommentary: 'Press START and jump on this golden mushroom question!',
    funFact: '2013 was officially celebrated by Nintendo as the "Year of Luigi".',
  },
  {
    id: 'pop_e2',
    question: 'Who created the Marvel Comics superhero character Spider-Man alongside artist Steve Ditko?',
    options: ['Jack Kirby', 'Stan Lee', 'Bob Kane', 'Jerry Siegel'],
    correctIndex: 1,
    correctAnswer: 'Stan Lee',
    explanation: 'Stan Lee and Steve Ditko introduced Peter Parker in Amazing Fantasy #15 in 1962.',
    category: 'pop_culture_gaming',
    difficulty: 'Easy',
    hostCommentary: 'Your Spider-Sense better be tingling for the right pick!',
    funFact: 'Stan Lee originally came up with the idea after watching a fly climb up a wall in his office.',
  },
  {
    id: 'pop_m1',
    question: 'Which movie won the Academy Award for Best Picture in 2020, becoming the first non-English winner?',
    options: ['Roma', 'Parasite', '1917', 'Drive My Car'],
    correctIndex: 1,
    correctAnswer: 'Parasite',
    explanation: 'Bong Joon-ho’s South Korean masterpiece "Parasite" swept the 92nd Academy Awards.',
    category: 'pop_culture_gaming',
    difficulty: 'Medium',
    hostCommentary: 'Lights, camera, cinephile action! Make the director proud.',
    funFact: 'Parasite won 4 Oscars that night: Best Picture, Best Director, Best Original Screenplay, and International Feature.',
  },
  {
    id: 'pop_m2',
    question: 'In the game "Minecraft", what mineral is required to craft Netherite ingots?',
    options: ['Obsidian', 'Ancient Debris', 'Bedrock', 'Crying Obsidian'],
    correctIndex: 1,
    correctAnswer: 'Ancient Debris',
    explanation: 'Ancient Debris must be smelted into Netherite Scrap, then combined with gold ingots.',
    category: 'pop_culture_gaming',
    difficulty: 'Medium',
    hostCommentary: 'Craft your way to victory before a Creeper sneaks up behind you!',
    funFact: 'Ancient Debris is immune to lava and will float safely to the surface if dropped.',
  },
  {
    id: 'pop_h1',
    question: 'What was the code name of the Nintendo 64 console during its development?',
    options: ['Project Reality', 'Dolphin', 'Revolution', 'Ultra 64'],
    correctIndex: 0,
    correctAnswer: 'Project Reality',
    explanation: 'It was co-developed with Silicon Graphics under the codename "Project Reality" before being shown as Ultra 64.',
    category: 'pop_culture_gaming',
    difficulty: 'Hard',
    hostCommentary: 'Only retro gaming historians know the secrets of 90s console wars!',
    funFact: 'The system was known as the Ultra 64 until shortly before release when Konami held trademark rights.',
  },
  {
    id: 'pop_h2',
    question: 'Which music artist holds the record for the most Grammy Awards won in history?',
    options: ['Georg Solti', 'Quincy Jones', 'Beyoncé', 'Paul McCartney'],
    correctIndex: 2,
    correctAnswer: 'Beyoncé',
    explanation: 'Beyoncé broke the all-time Grammy record in 2023, surpassing conductor Georg Solti with 32+ wins.',
    category: 'pop_culture_gaming',
    difficulty: 'Hard',
    hostCommentary: 'Listen to the rhythm of musical history and strike a chord!',
    funFact: 'She won her historic 32nd Grammy for Best Dance/Electronic Album for "Renaissance".',
  },

  // ==================== LITERATURE & ARTS ====================
  {
    id: 'lit_e1',
    question: 'Who wrote the tragedy "Romeo and Juliet"?',
    options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
    correctIndex: 1,
    correctAnswer: 'William Shakespeare',
    explanation: 'William Shakespeare penned Romeo and Juliet early in his career around 1595.',
    category: 'literature_arts',
    difficulty: 'Easy',
    hostCommentary: 'To be right, or not to be right—that is the question!',
    funFact: 'Shakespeare invented over 1,700 common English words, including "eyeball", "swagger", and "lonely".',
  },
  {
    id: 'lit_e2',
    question: 'Which artist painted the famous ceiling frescoes of the Sistine Chapel in Rome?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'],
    correctIndex: 1,
    correctAnswer: 'Michelangelo',
    explanation: 'Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512 under Pope Julius II.',
    category: 'literature_arts',
    difficulty: 'Easy',
    hostCommentary: 'Reach out and touch the spark of divine knowledge!',
    funFact: 'Contrary to popular belief, Michelangelo painted standing on specially designed scaffolds, not lying down.',
  },
  {
    id: 'lit_m1',
    question: 'In George Orwell’s dystopian novel "1984", what is the primary slogan of the Party in Ingsoc?',
    options: [
      'Knowledge is Power',
      'War is Peace, Freedom is Slavery, Ignorance is Strength',
      'Order Brings Prosperity',
      'Obedience is Loyalty'
    ],
    correctIndex: 1,
    correctAnswer: 'War is Peace, Freedom is Slavery, Ignorance is Strength',
    explanation: 'The three slogans of the Party are engraved on the white pyramid of the Ministry of Truth.',
    category: 'literature_arts',
    difficulty: 'Medium',
    hostCommentary: 'Big Brother is watching your score closely right now!',
    funFact: 'Orwell’s working title for the manuscript was originally "The Last Man in Europe".',
  },
  {
    id: 'lit_m2',
    question: 'Which painter sliced off part of his own left ear in Arles in December 1888?',
    options: ['Claude Monet', 'Vincent van Gogh', 'Paul Gauguin', 'Pablo Picasso'],
    correctIndex: 1,
    correctAnswer: 'Vincent van Gogh',
    explanation: 'Vincent van Gogh cut off part of his ear after an intense quarrel with fellow painter Paul Gauguin.',
    category: 'literature_arts',
    difficulty: 'Medium',
    hostCommentary: 'A brush with madness and genius! Keep your senses intact.',
    funFact: 'Van Gogh sold only one known painting during his lifetime, "The Red Vineyard", for 400 francs.',
  },
  {
    id: 'lit_h1',
    question: 'Who wrote the epic 14th-century Italian allegorical poem "The Divine Comedy"?',
    options: ['Petrarch', 'Giovanni Boccaccio', 'Dante Alighieri', 'Niccolò Machiavelli'],
    correctIndex: 2,
    correctAnswer: 'Dante Alighieri',
    explanation: 'Dante Alighieri wrote the Comedìa (later dubbed Divina by Boccaccio) in the Florentine dialect.',
    category: 'literature_arts',
    difficulty: 'Hard',
    hostCommentary: 'Journey through Inferno and Purgatorio to ascend to trivia Paradiso!',
    funFact: 'Dante established the Tuscan dialect as the standardized basis for the modern Italian language.',
  },
  {
    id: 'lit_h2',
    question: 'Which sculpture by Auguste Rodin portrays a man in deep meditation battling with a powerful internal struggle?',
    options: ['The Kiss', 'The Thinker', 'The Burghers of Calais', 'Gates of Hell'],
    correctIndex: 1,
    correctAnswer: 'The Thinker',
    explanation: 'Originally titled "The Poet", Rodin conceived "The Thinker" as a representation of Dante.',
    category: 'literature_arts',
    difficulty: 'Hard',
    hostCommentary: 'Put your hand on your chin and deliberate deeply.',
    funFact: 'There are more than 25 life-sized bronze castings of The Thinker in museums and gardens worldwide.',
  },

  // ==================== BREAKING NEWS & TECH ====================
  {
    id: 'news_e1',
    question: 'What does the acronym "AI" stand for in modern computer science?',
    options: ['Automated Interface', 'Artificial Intelligence', 'Algorithmic Integration', 'Applied Informatics'],
    correctIndex: 1,
    correctAnswer: 'Artificial Intelligence',
    explanation: 'Artificial Intelligence refers to computer systems engineered to simulate human intelligence.',
    category: 'breaking_news',
    difficulty: 'Easy',
    hostCommentary: 'You are playing against an AI right now, so you better know this one!',
    funFact: 'The term "Artificial Intelligence" was first coined at the Dartmouth Summer Workshop in 1956.',
  },
  {
    id: 'news_e2',
    question: 'Which international space agency launched the revolutionary James Webb Space Telescope?',
    options: ['NASA with ESA and CSA', 'Roscosmos', 'ISRO', 'JAXA alone'],
    correctIndex: 0,
    correctAnswer: 'NASA with ESA and CSA',
    explanation: 'The JWST was built through international collaboration between NASA, ESA, and the Canadian Space Agency.',
    category: 'breaking_news',
    difficulty: 'Easy',
    hostCommentary: 'Peer back in time to the dawn of the cosmic universe!',
    funFact: 'The JWST orbits the Sun at the Second Lagrange Point (L2), roughly 1.5 million kilometers from Earth.',
  },
  {
    id: 'news_m1',
    question: 'What is the name of the transformative neural network architecture introduced by Google researchers in 2017?',
    options: ['ResNet', 'Transformer', 'Perceptron', 'LSTM'],
    correctIndex: 1,
    correctAnswer: 'Transformer',
    explanation: 'Introduced in the landmark paper "Attention Is All You Need", Transformers underpin modern LLMs.',
    category: 'breaking_news',
    difficulty: 'Medium',
    hostCommentary: 'Self-attention mechanisms activated! Focus your attention on the prize.',
    funFact: 'The 2017 paper has been cited over 150,000 times across academic research.',
  },
  {
    id: 'news_m2',
    question: 'In what year did the Paris Climate Agreement enter into legal force internationally?',
    options: ['2015', '2016', '2018', '2021'],
    correctIndex: 1,
    correctAnswer: '2016',
    explanation: 'Adopted in December 2015, the agreement reached its ratification threshold and took effect in November 2016.',
    category: 'breaking_news',
    difficulty: 'Medium',
    hostCommentary: 'Global treaties and environmental pacts—staying informed pays off!',
    funFact: 'Over 195 nations signed the agreement, aiming to limit warming well below 2°C above pre-industrial levels.',
  },
  {
    id: 'news_h1',
    question: 'What quantum computing metric, achieved by Google in 2019, proved a quantum processor could outperform classical supercomputers?',
    options: ['Quantum Supremacy', 'Quantum Entanglement Limit', 'Shor Bound', 'Qubit Coherence Horizon'],
    correctIndex: 0,
    correctAnswer: 'Quantum Supremacy',
    explanation: 'Google’s 53-qubit Sycamore processor performed a target calculation in 200 seconds that would take years on a supercomputer.',
    category: 'breaking_news',
    difficulty: 'Hard',
    hostCommentary: 'Superposition, entanglement, and quantum superiority on the clock!',
    funFact: 'Sycamore operated at cryogenically frozen temperatures near absolute zero (-273.1°C).',
  },
  {
    id: 'news_h2',
    question: 'Which lunar crater at the Moon’s South Pole was the target landing site of India’s historic Chandrayaan-3 mission?',
    options: ['Tycho Crater', 'Manzinus U crater', 'Between Manzinus C and Simpelius N', 'Shackleton Crater'],
    correctIndex: 2,
    correctAnswer: 'Between Manzinus C and Simpelius N',
    explanation: 'Chandrayaan-3 successfully touched down on August 23, 2023 near 69.37° S latitude.',
    category: 'breaking_news',
    difficulty: 'Hard',
    hostCommentary: 'Precision orbital mechanics and south-pole lunar exploration!',
    funFact: 'India became the very first nation to land a spacecraft successfully near the lunar south pole.',
  },

  // ==================== ALL MIX & GENERAL KNOWLEDGE ====================
  {
    id: 'mix_e1',
    question: 'How many sides does an octagon have?',
    options: ['6', '7', '8', '10'],
    correctIndex: 2,
    correctAnswer: '8',
    explanation: 'An octagon is an eight-sided polygon, famously seen in standard STOP traffic signs.',
    category: 'all_mix',
    difficulty: 'Easy',
    hostCommentary: 'Stop right there! Don’t overthink this geometric classic.',
    funFact: 'The interior angles of a regular octagon always add up to exactly 1080 degrees.',
  },
  {
    id: 'mix_e2',
    question: 'Which is the only mammal capable of true, sustained flapping flight?',
    options: ['Flying Squirrel', 'Sugar Glider', 'Bat', 'Colugo'],
    correctIndex: 2,
    correctAnswer: 'Bat',
    explanation: 'Bats are the only mammals capable of powered flight; others like flying squirrels merely glide.',
    category: 'all_mix',
    difficulty: 'Easy',
    hostCommentary: 'Spread your wings and take flight with the correct answer!',
    funFact: 'Bats make up approximately 20% of all classified mammal species worldwide.',
  },
  {
    id: 'mix_m1',
    question: 'In chess, which piece can move only diagonally across the board?',
    options: ['Knight', 'Bishop', 'Rook', 'Pawn'],
    correctIndex: 1,
    correctAnswer: 'Bishop',
    explanation: 'Bishops move any number of vacant squares along diagonal lines of the same color.',
    category: 'all_mix',
    difficulty: 'Medium',
    hostCommentary: 'A strategic move on the board! Checkmate your opponents.',
    funFact: 'Because they only move diagonally, a bishop can never reach 32 of the 64 squares on the board.',
  },
  {
    id: 'mix_m2',
    question: 'What is the currency of Japan?',
    options: ['Won', 'Yuan', 'Yen', 'Ringgit'],
    correctIndex: 2,
    correctAnswer: 'Yen',
    explanation: 'The Japanese yen (symbol: ¥) is the official currency of Japan and one of the world’s most traded currencies.',
    category: 'all_mix',
    difficulty: 'Medium',
    hostCommentary: 'Cash in on your international knowledge!',
    funFact: 'The word "yen" translates literally to "round object" or "circle" in Japanese.',
  },
  {
    id: 'mix_h1',
    question: 'What is the rarest blood type among human populations worldwide?',
    options: ['O Negative', 'B Negative', 'AB Negative', 'A Negative'],
    correctIndex: 2,
    correctAnswer: 'AB Negative',
    explanation: 'AB Negative is found in less than 1% of the world population.',
    category: 'all_mix',
    difficulty: 'Hard',
    hostCommentary: 'Pure hematological rarity! Does your trivia blood run cold or gold?',
    funFact: 'People with AB Positive blood are universal plasma recipients, while O Negative are universal red blood cell donors.',
  },
  {
    id: 'mix_h2',
    question: 'Which famous mathematical constant is approximately equal to 2.71828?',
    options: ['Pi (π)', 'Euler’s Number (e)', 'Golden Ratio (φ)', 'Feigenbaum Constant (δ)'],
    correctIndex: 1,
    correctAnswer: 'Euler’s Number (e)',
    explanation: 'Euler’s number (e) is the base of the natural logarithm and represents continuous compound growth.',
    category: 'all_mix',
    difficulty: 'Hard',
    hostCommentary: 'Exponential intelligence is required to solve this equation!',
    funFact: 'The value of e was discovered by Jacob Bernoulli in 1683 while studying compound interest.',
  }
];
